from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from datetime import datetime
import io

def generate_report_pdf(patient_id, answers, result, diet_tips, exercise_tips):
    """Builds a PDF medical report in memory and returns it as bytes."""

    buffer = io.BytesIO()  # an in-memory "file" — we never need to save this to disk
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=2*cm, bottomMargin=2*cm)

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle('TitleStyle', parent=styles['Title'], textColor=colors.HexColor('#2B1B2E'))
    heading_style = ParagraphStyle('HeadingStyle', parent=styles['Heading2'], textColor=colors.HexColor('#6B4E9E'))
    normal_style = styles['Normal']

    elements = []

    # ---------- Header ----------
    elements.append(Paragraph('PCOSense — Medical Report', title_style))
    elements.append(Paragraph(f'Generated on {datetime.now().strftime("%d %B %Y, %I:%M %p")}', normal_style))
    elements.append(Spacer(1, 0.8*cm))

    # ---------- Patient Details Table ----------
    elements.append(Paragraph('Patient Details', heading_style))
    bmi = answers['weight'] / ((answers['height'] / 100) ** 2)
    patient_data = [
        ['Patient ID', patient_id],
        ['Age', f"{answers['age']} years"],
        ['Height', f"{answers['height']} cm"],
        ['Weight', f"{answers['weight']} kg"],
        ['BMI', f"{bmi:.1f}"],
    ]
    patient_table = Table(patient_data, colWidths=[6*cm, 10*cm])
    patient_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#F3E8F0')),
        ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#6B4E9E')),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E5D5DE')),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
    ]))
    elements.append(patient_table)
    elements.append(Spacer(1, 0.8*cm))

    # ---------- AI Prediction ----------
    elements.append(Paragraph('AI Risk Assessment', heading_style))
    risk_color = colors.HexColor('#C2578E') if result['prediction'] == 1 else colors.HexColor('#6B4E9E')
    risk_style = ParagraphStyle('RiskStyle', parent=styles['Heading1'], textColor=risk_color, fontSize=20)
    elements.append(Paragraph(result['risk_label'], risk_style))
    elements.append(Paragraph(f"Confidence: {result['confidence']}%", normal_style))
    elements.append(Paragraph('Based on 14 clinical and lifestyle factors analyzed by a trained Logistic Regression model.', normal_style))
    elements.append(Spacer(1, 0.8*cm))

    # ---------- Diet Plan ----------
    elements.append(Paragraph('Personalized Diet Plan', heading_style))
    for label, value in diet_tips.items():
        elements.append(Paragraph(f'<b>{label}:</b> {value}', normal_style))
    elements.append(Spacer(1, 0.8*cm))

    # ---------- Exercise Plan ----------
    elements.append(Paragraph('Personalized Exercise Plan', heading_style))
    for label, value in exercise_tips.items():
        elements.append(Paragraph(f'<b>{label}:</b> {value}', normal_style))
    elements.append(Spacer(1, 0.8*cm))

    # ---------- Footer note ----------
    disclaimer_style = ParagraphStyle('Disclaimer', parent=styles['Normal'], fontSize=8, textColor=colors.grey)
    elements.append(Spacer(1, 1*cm))
    elements.append(Paragraph(
        'This report is generated by an AI screening tool and is not a substitute for professional '
        'medical diagnosis. Please consult a qualified healthcare provider for clinical evaluation.',
        disclaimer_style
    ))

    doc.build(elements)
    buffer.seek(0)  
    return buffer